// Pixel art palette and frame matrices generator
// Explicit discrete sprite frames for Knight, Enemies, Weapons, Tiles, and Items

export const PALETTE = {
  // Knight
  kArmorLight: '#c2c9d6',
  kArmorMid: '#7e8a9c',
  kArmorDark: '#454e5f',
  kArmorDeep: '#232733',
  kGoldLight: '#facc15',
  kGoldDark: '#ca8a04',
  kVisor: '#38bdf8',
  kVisorGlow: '#bae6fd',
  kPlume: '#ef4444',
  kPlumeDark: '#991b1b',
  kCape: '#dc2626',
  kCapeDark: '#7f1d1d',
  kSkin: '#fed7aa',
  kBoots: '#57534e',
  kBootsDark: '#292524',
  
  // Zombie
  zSkin: '#4ade80',
  zSkinDark: '#15803d',
  zSkinRot: '#14532d',
  zEye: '#f87171',
  zShirt: '#3b82f6',
  zShirtDark: '#1d4ed8',
  zPants: '#6b21a8',
  zPantsDark: '#3b0764',
  zBone: '#e2e8f0',

  // Armored Zombie
  azHelm: '#94a3b8',
  azHelmDark: '#475569',
  azRust: '#b45309',

  // Boss Brute Zombie
  bzSkin: '#22c55e',
  bzSkinDark: '#166534',
  bzGlow: '#ef4444',

  // Crawler / Blood Zombie
  crSkin: '#dc2626',
  crSkinDark: '#7f1d1d',
  crEye: '#fef08a',

  // Merchant
  mSkin: '#fcd34d',
  mBeard: '#f8fafc',
  mCoat: '#1e3a8a',
  mCoatTrim: '#fbbf24',
  mHat: '#1e40af',

  // Environment & Blocks
  stoneLight: '#94a3b8',
  stoneMid: '#64748b',
  stoneDark: '#334155',
  stoneGrout: '#1e293b',
  dirt: '#78350f',
  dirtDark: '#451a03',
  grass: '#22c55e',
  grassDark: '#15803d',
  wood: '#a16207',
  woodDark: '#713f12',
  woodLight: '#ca8a04',
  brickLight: '#78716c',
  brickMid: '#57534e',
  brickDark: '#292524',
  torchWood: '#713f12',
  torchFire1: '#fef08a',
  torchFire2: '#f97316',
  torchFire3: '#ef4444',
  
  // Items & Metals
  copper: '#d97706',
  copperDark: '#92400e',
  iron: '#cbd5e1',
  ironDark: '#64748b',
  gold: '#fbbf24',
  goldDark: '#b45309',
  fireOre: '#f97316',
  fireOreDark: '#c2410c',
  darkShard: '#a855f7',
  darkShardDark: '#581c87',
  potionRed: '#ef4444',
  potionGlass: '#93c5fd',

  // FX
  slashWhite: '#ffffff',
  slashCyan: '#67e8f9',
  slashFire: '#fdba74',
  slashShadow: '#c084fc',
};

// Helper to convert ascii pixel strings to OffscreenCanvas
export function createPixelSprite(asciiArt, colorMap, pixelSize = 2) {
  const lines = asciiArt.trim().split('\n').map(l => l.trimEnd());
  const height = lines.length;
  const width = Math.max(...lines.map(l => l.length));

  const canvas = document.createElement('canvas');
  canvas.width = width * pixelSize;
  canvas.height = height * pixelSize;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;

  for (let y = 0; y < height; y++) {
    const line = lines[y];
    for (let x = 0; x < line.length; x++) {
      const char = line[x];
      if (char && char !== ' ' && char !== '.') {
        const color = colorMap[char];
        if (color) {
          ctx.fillStyle = color;
          ctx.fillRect(x * pixelSize, y * pixelSize, pixelSize, pixelSize);
        }
      }
    }
  }

  return canvas;
}

// -------------------------------------------------------------
// KNIGHT SPRITE FRAMES (Separately Handcrafted Discrete Frames)
// -------------------------------------------------------------
const K_MAP = {
  'H': PALETTE.kArmorLight,
  'h': PALETTE.kArmorMid,
  'D': PALETTE.kArmorDark,
  'd': PALETTE.kArmorDeep,
  'G': PALETTE.kGoldLight,
  'g': PALETTE.kGoldDark,
  'V': PALETTE.kVisorGlow,
  'v': PALETTE.kVisor,
  'P': PALETTE.kPlume,
  'p': PALETTE.kPlumeDark,
  'C': PALETTE.kCape,
  'c': PALETTE.kCapeDark,
  'S': PALETTE.kSkin,
  'B': PALETTE.kBoots,
  'b': PALETTE.kBootsDark,
  'W': '#ffffff',
};

// Knight Idle Frame 1
const KNIGHT_IDLE_1 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhd....
.CShhHhdG...
.CChhhhdGG..
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Idle Frame 2 (Breathing / plume subtle shift)
const KNIGHT_IDLE_2 = `
...PPp......
..PPPpp.....
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhd....
.CShhHhdG...
.CChhhhdGG..
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Idle Frame 3
const KNIGHT_IDLE_3 = `
....PP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhd....
.CShhHhdG...
.CChhhhdGG..
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Idle Frame 4
const KNIGHT_IDLE_4 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhd....
.CShhHhdG...
.CChhhhdGG..
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Run Frame 1
const KNIGHT_RUN_1 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.cChhhhd....
..CdDDdd....
.BBD..db....
.BBD...bb...
.bb.........
............
`;

// Knight Run Frame 2
const KNIGHT_RUN_2 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.cChhhhd....
..CdDDdd....
..BBD.bb....
..BBD.bb....
...bb.......
............
`;

// Knight Run Frame 3
const KNIGHT_RUN_3 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.cChhhhd....
..CdDDdd....
...dD.BBD...
...dd.BBD...
.......bb...
............
`;

// Knight Run Frame 4
const KNIGHT_RUN_4 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.cChhhhd....
..CdDDdd....
..db..BBD...
.bb...BBD...
.......bb...
............
`;

// Knight Run Frame 5
const KNIGHT_RUN_5 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.cChhhhd....
..CdDDdd....
..bb..BBD...
..bb..BBD...
.......bb...
............
`;

// Knight Run Frame 6
const KNIGHT_RUN_6 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.cChhhhd....
..CdDDdd....
.BBD..db....
.BBD...bb...
..bb........
............
`;

// Knight Jump Frame
const KNIGHT_JUMP = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhdGG..
.CChhHhd....
.CChhhhd....
..CdDDdd....
.BBD..BBD...
.bb....bb...
............
............
`;

// Knight Fall Frame
const KNIGHT_FALL = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
CCShHHhdGG..
cCChhHhd....
.CChhhhd....
..CdDDdd....
..BBDdbb....
..BBDdbb....
...bb.bb....
............
`;

// Knight Attack Frame 1 (Windup)
const KNIGHT_ATTACK_1 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhd....
.CShhHhdG...
.CChhhhdGG..
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Attack Frame 2 (Thrust / Slash forward)
const KNIGHT_ATTACK_2 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
..ShHHhdGGGG
.CShhHhd....
.CChhhhd....
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Attack Frame 3 (Follow-through)
const KNIGHT_ATTACK_3 = `
...PPP......
..PPpp......
.HHhhhhG....
.HhVvvvd....
.Hhhhhhh....
.CShHHhd....
.CShhHhd....
.CChhhhdGGGG
.Cchhhhd....
..CdDDdd....
..cdDDdd....
..BBDdbb....
..BBDdbb....
`;

// Knight Hurt Frame
const KNIGHT_HURT = `
...PPP......
..PPpp......
.WWhhhhG....
.WhWvvvd....
.Whhhhhh....
.WShHHhd....
.WShhHhdG...
.WWhhhhdGG..
.Wchhhhd....
..WdDDdd....
..wdDDdd....
..WWDdbb....
..WWDdbb....
`;

// -------------------------------------------------------------
// ENEMY SPRITES (Zombies, Armored, Crawler, Brute Boss)
// -------------------------------------------------------------
const Z_MAP = {
  'S': PALETTE.zSkin,
  's': PALETTE.zSkinDark,
  'R': PALETTE.zSkinRot,
  'E': PALETTE.zEye,
  'T': PALETTE.zShirt,
  't': PALETTE.zShirtDark,
  'P': PALETTE.zPants,
  'p': PALETTE.zPantsDark,
  'B': PALETTE.zBone,
  'H': PALETTE.azHelm,
  'h': PALETTE.azHelmDark,
  'U': PALETTE.azRust,
  'W': '#ffffff',
  'C': PALETTE.crSkin,
  'c': PALETTE.crSkinDark,
  'Y': PALETTE.crEye,
  'G': PALETTE.bzGlow,
};

// Zombie Walk 1
const ZOMBIE_WALK_1 = `
...SSss.....
..SSSSss....
.SRSSEss....
.SSSSsss....
..SSsss.....
.ssssTTTSS..
.ssTTTTTSS..
..tTTtTT....
..tTTttT....
..PPPPpp....
..PP..pp....
..pp...pp...
`;

// Zombie Walk 2
const ZOMBIE_WALK_2 = `
...SSss.....
..SSSSss....
.SRSSEss....
.SSSSsss....
..SSsss.....
.ssssTTTSS..
.ssTTTTTSS..
..tTTtTT....
..tTTttT....
..PPPPpp....
...PP.pp....
...pp.pp....
`;

// Zombie Walk 3
const ZOMBIE_WALK_3 = `
...SSss.....
..SSSSss....
.SRSSEss....
.SSSSsss....
..SSsss.....
.ssssTTTSS..
.ssTTTTTSS..
..tTTtTT....
..tTTttT....
..PPPPpp....
..pp..PP....
.pp....pp...
`;

// Zombie Walk 4
const ZOMBIE_WALK_4 = `
...SSss.....
..SSSSss....
.SRSSEss....
.SSSSsss....
..SSsss.....
.ssssTTTSS..
.ssTTTTTSS..
..tTTtTT....
..tTTttT....
..PPPPpp....
..pp..PP....
..pp..pp....
`;

// Zombie Hurt
const ZOMBIE_HURT = `
...WWss.....
..WWWWss....
.WRWSEss....
.WWWWsss....
..WWsss.....
.ssssTTTWW..
.ssTTTTTWW..
..tTTtTT....
..tTTttT....
..PPPPpp....
..PP..pp....
..pp...pp...
`;

// Armored Zombie Walk 1
const ARMORED_ZOMBIE_1 = `
...HHhh.....
..HHHHhh....
.HUHHEhh....
.HHHHhhh....
..SSsss.....
.hhhhTTTHH..
.hhTTTTTHH..
..hTThTT....
..hTThtT....
..hhhhpp....
..hh..pp....
..hh...pp...
`;

const ARMORED_ZOMBIE_2 = `
...HHhh.....
..HHHHhh....
.HUHHEhh....
.HHHHhhh....
..SSsss.....
.hhhhTTTHH..
.hhTTTTTHH..
..hTThTT....
..hTThtT....
..hhhhpp....
...hh.pp....
...hh.pp....
`;

const ARMORED_ZOMBIE_3 = `
...HHhh.....
..HHHHhh....
.HUHHEhh....
.HHHHhhh....
..SSsss.....
.hhhhTTTHH..
.hhTTTTTHH..
..hTThTT....
..hTThtT....
..hhhhpp....
..pp..hh....
.pp....hh...
`;

const ARMORED_ZOMBIE_4 = `
...HHhh.....
..HHHHhh....
.HUHHEhh....
.HHHHhhh....
..SSsss.....
.hhhhTTTHH..
.hhTTTTTHH..
..hTThTT....
..hTThtT....
..hhhhpp....
..pp..hh....
..pp..hh....
`;

// Crawler Frame 1 & 2
const CRAWLER_1 = `
............
....CCcc....
...CCCCcc...
..CcYCCcYc..
.CCcCCCCCCc.
.ccccCCCCCC.
..cc.cc.cc..
.cc..cc..cc.
`;

const CRAWLER_2 = `
............
....CCcc....
...CCCCcc...
..CcYCCcYc..
.CCcCCCCCCc.
.ccccCCCCCC.
.cc..cc..cc.
..cc.cc.cc..
`;

// Brute Zombie (Large miniboss)
const BRUTE_1 = `
....SSSSssss....
...SSSSSSssss...
..SSRRSGEssss...
..SSSSSSGGsss...
...SSSSsssss....
.sssssTTTTSSSS..
.sssssTTTTSSSS..
.ssTTTTTTTTSSS..
.ssTTTTTTTTSSS..
..ttTTTtTTtt....
..ttTTTttTtt....
..PPPPPPpppp....
..PPPP..pppp....
..PPPP..pppp....
..pppp...pppp...
..pppp...pppp...
`;

const BRUTE_2 = `
....SSSSssss....
...SSSSSSssss...
..SSRRSGEssss...
..SSSSSSGGsss...
...SSSSsssss....
.sssssTTTTSSSS..
.sssssTTTTSSSS..
.ssTTTTTTTTSSS..
.ssTTTTTTTTSSS..
..ttTTTtTTtt....
..ttTTTttTtt....
..PPPPPPpppp....
...PPPP.pppp....
...PPPP.pppp....
...pppp.pppp....
...pppp.pppp....
`;

// -------------------------------------------------------------
// NPC / MERCHANT SPRITE
// -------------------------------------------------------------
const M_MAP = {
  'S': PALETTE.mSkin,
  'B': PALETTE.mBeard,
  'C': PALETTE.mCoat,
  'T': PALETTE.mCoatTrim,
  'H': PALETTE.mHat,
  'G': PALETTE.kGoldLight,
};

const MERCHANT_IDLE_1 = `
...HHHHH....
..HHHHHHH...
...SSSSS....
...SESES....
...SBBBS....
...BBBBB....
..CTTTTTC...
.CCTTCCTTCC.
.CCTTCCTTCC.
..CCTTCCTT..
...CCCCCC...
...BB..BB...
`;

const MERCHANT_IDLE_2 = `
...HHHHH....
..HHHHHHH...
...SSSSS....
...SESES....
...SBBBS....
...BBBBB....
..CTTTTTC...
.CCTTCCTTCC.
.CCTTCCTTCC.
..CCTTCCTT..
...CCCCCC...
...BB..BB...
`;

// -------------------------------------------------------------
// WEAPONS PIXEL ART
// -------------------------------------------------------------
const W_MAP = {
  'c': PALETTE.copperDark,
  'C': PALETTE.copper,
  'i': PALETTE.ironDark,
  'I': PALETTE.iron,
  'g': PALETTE.goldDark,
  'G': PALETTE.gold,
  'w': PALETTE.woodDark,
  'W': PALETTE.woodLight,
  'f': PALETTE.fireOreDark,
  'F': PALETTE.fireOre,
  'Y': '#fef08a',
  'd': PALETTE.darkShardDark,
  'D': PALETTE.darkShard,
  'M': '#e879f9',
};

// Copper Shortsword
const WEAPON_COPPER_SWORD = `
......CC
.....CCC
....CCC.
...CCC..
..CCC...
.wCc....
w.w.....
`;

// Iron Broadsword
const WEAPON_IRON_SWORD = `
.......II
......III
.....III.
....III..
...III...
..wIiw...
.w.w.....
w..w.....
`;

// Gold Longsword
const WEAPON_GOLD_SWORD = `
........GG
.......GGG
......GGG.
.....GGG..
....GGG...
...GGG....
..wGgw....
.w.w......
w..w......
`;

// Fiery Greatsword
const WEAPON_FIRE_SWORD = `
.........FY
........FFY
.......FFF.
......FFF..
.....FFF...
....FFF....
...FFF.....
..wFfw.....
.w.w.......
w..w.......
`;

// Night's Edge
const WEAPON_NIGHTS_EDGE = `
.........DM
........DDM
.......DDD.
......DDD..
.....DDD...
....DDD....
...DDD.....
..wDdw.....
.w.w.......
w..w.......
`;

// Wooden Bow
const WEAPON_BOW = `
...WW...
..W..W..
.W....i.
W.....i.
.W....i.
..W..W..
...WW...
`;

// -------------------------------------------------------------
// TILES & OBJECTS (Dirt, Stone, Wood Platform, Torch, Anvil, Coins)
// -------------------------------------------------------------
const TILE_DIRT_GRASS = `
GGgGGGGgGGgGGGGg
GGGGgGGGGGGgGGGG
ddDddddDddddDddd
dddddddddddddddd
dDddddDddddDdddd
dddddddddddddddd
ddDddddDddddDddd
dddddddddddddddd
`;

const TILE_STONE_BRICK = `
LLLLLLLLgLLLLLLL
LMMMMMLMgLMMMMML
LMMMMMLMgLMMMMML
gggggggggggggggg
LLLLgLLLLLLLLgLL
LMMMgLMMMMMLMgLM
LMMMgLMMMMMLMgLM
gggggggggggggggg
`;

const TILE_WOOD_PLATFORM = `
WWWWWwWWWWWWwWWW
WwwwwwWwwwwwwWww
.W...W..W...W...
.W...W..W...W...
`;

const TORCH_1 = `
...Y...
..YYF..
..YFF..
...w...
...w...
...w...
`;

const TORCH_2 = `
...F...
..FYY..
..FFY..
...w...
...w...
...w...
`;

const TORCH_3 = `
..YY...
..YYF..
..FFF..
...w...
...w...
...w...
`;

const ANVIL = `
.IIIIIIIIII.
IIIIIIIIIIII
..iIIIIIIi..
...iIIIIi...
..IIIIIIII..
.IIIIIIIIII.
`;

const COIN_COPPER = `
.CCC.
CCCCC
CCCCC
.CCC.
`;

const COIN_SILVER = `
.III.
IIIII
IIIII
.III.
`;

const COIN_GOLD = `
.GGG.
GGGGG
GGGGG
.GGG.
`;

const HEART_CONTAINER = `
.RR.RR.
RRRRRRR
RRRRRRR
.RRRRR.
..RRR..
...R...
`;

// Pre-render and bundle all discrete sprites
export class SpriteStore {
  constructor() {
    this.sprites = {};
    this.init();
  }

  init() {
    // Knight discrete frames
    this.sprites['knight_idle_0'] = createPixelSprite(KNIGHT_IDLE_1, K_MAP);
    this.sprites['knight_idle_1'] = createPixelSprite(KNIGHT_IDLE_2, K_MAP);
    this.sprites['knight_idle_2'] = createPixelSprite(KNIGHT_IDLE_3, K_MAP);
    this.sprites['knight_idle_3'] = createPixelSprite(KNIGHT_IDLE_4, K_MAP);

    this.sprites['knight_run_0'] = createPixelSprite(KNIGHT_RUN_1, K_MAP);
    this.sprites['knight_run_1'] = createPixelSprite(KNIGHT_RUN_2, K_MAP);
    this.sprites['knight_run_2'] = createPixelSprite(KNIGHT_RUN_3, K_MAP);
    this.sprites['knight_run_3'] = createPixelSprite(KNIGHT_RUN_4, K_MAP);
    this.sprites['knight_run_4'] = createPixelSprite(KNIGHT_RUN_5, K_MAP);
    this.sprites['knight_run_5'] = createPixelSprite(KNIGHT_RUN_6, K_MAP);

    this.sprites['knight_jump'] = createPixelSprite(KNIGHT_JUMP, K_MAP);
    this.sprites['knight_fall'] = createPixelSprite(KNIGHT_FALL, K_MAP);

    this.sprites['knight_attack_0'] = createPixelSprite(KNIGHT_ATTACK_1, K_MAP);
    this.sprites['knight_attack_1'] = createPixelSprite(KNIGHT_ATTACK_2, K_MAP);
    this.sprites['knight_attack_2'] = createPixelSprite(KNIGHT_ATTACK_3, K_MAP);

    this.sprites['knight_hurt'] = createPixelSprite(KNIGHT_HURT, K_MAP);

    // Zombies
    this.sprites['zombie_0'] = createPixelSprite(ZOMBIE_WALK_1, Z_MAP);
    this.sprites['zombie_1'] = createPixelSprite(ZOMBIE_WALK_2, Z_MAP);
    this.sprites['zombie_2'] = createPixelSprite(ZOMBIE_WALK_3, Z_MAP);
    this.sprites['zombie_3'] = createPixelSprite(ZOMBIE_WALK_4, Z_MAP);
    this.sprites['zombie_hurt'] = createPixelSprite(ZOMBIE_HURT, Z_MAP);

    // Armored Zombies
    this.sprites['armored_zombie_0'] = createPixelSprite(ARMORED_ZOMBIE_1, Z_MAP);
    this.sprites['armored_zombie_1'] = createPixelSprite(ARMORED_ZOMBIE_2, Z_MAP);
    this.sprites['armored_zombie_2'] = createPixelSprite(ARMORED_ZOMBIE_3, Z_MAP);
    this.sprites['armored_zombie_3'] = createPixelSprite(ARMORED_ZOMBIE_4, Z_MAP);

    // Crawlers
    this.sprites['crawler_0'] = createPixelSprite(CRAWLER_1, Z_MAP);
    this.sprites['crawler_1'] = createPixelSprite(CRAWLER_2, Z_MAP);

    // Brute Boss
    this.sprites['brute_0'] = createPixelSprite(BRUTE_1, Z_MAP, 3);
    this.sprites['brute_1'] = createPixelSprite(BRUTE_2, Z_MAP, 3);

    // Merchant
    this.sprites['merchant_0'] = createPixelSprite(MERCHANT_IDLE_1, M_MAP);
    this.sprites['merchant_1'] = createPixelSprite(MERCHANT_IDLE_2, M_MAP);

    // Weapons
    this.sprites['sword_copper'] = createPixelSprite(WEAPON_COPPER_SWORD, W_MAP);
    this.sprites['sword_iron'] = createPixelSprite(WEAPON_IRON_SWORD, W_MAP);
    this.sprites['sword_gold'] = createPixelSprite(WEAPON_GOLD_SWORD, W_MAP);
    this.sprites['sword_fire'] = createPixelSprite(WEAPON_FIRE_SWORD, W_MAP);
    this.sprites['sword_night'] = createPixelSprite(WEAPON_NIGHTS_EDGE, W_MAP);
    this.sprites['weapon_bow'] = createPixelSprite(WEAPON_BOW, W_MAP);

    // Tiles & Objects
    const tileMap = {
      'G': PALETTE.grass,
      'g': PALETTE.grassDark,
      'd': PALETTE.dirt,
      'D': PALETTE.dirtDark,
      'L': PALETTE.stoneLight,
      'M': PALETTE.stoneMid,
      'W': PALETTE.wood,
      'w': PALETTE.woodDark,
      'Y': PALETTE.torchFire1,
      'F': PALETTE.torchFire2,
      'I': PALETTE.iron,
      'i': PALETTE.ironDark,
      'C': PALETTE.copper,
      'R': '#ef4444',
    };
    this.sprites['tile_grass'] = createPixelSprite(TILE_DIRT_GRASS, tileMap, 2);
    this.sprites['tile_stone'] = createPixelSprite(TILE_STONE_BRICK, tileMap, 2);
    this.sprites['tile_platform'] = createPixelSprite(TILE_WOOD_PLATFORM, tileMap, 2);

    this.sprites['torch_0'] = createPixelSprite(TORCH_1, tileMap, 2);
    this.sprites['torch_1'] = createPixelSprite(TORCH_2, tileMap, 2);
    this.sprites['torch_2'] = createPixelSprite(TORCH_3, tileMap, 2);

    this.sprites['anvil'] = createPixelSprite(ANVIL, tileMap, 2);

    // Drops & Items
    this.sprites['coin_copper'] = createPixelSprite(COIN_COPPER, tileMap, 2);
    this.sprites['coin_silver'] = createPixelSprite(COIN_SILVER, tileMap, 2);
    this.sprites['coin_gold'] = createPixelSprite(COIN_GOLD, tileMap, 2);
    this.sprites['heart'] = createPixelSprite(HEART_CONTAINER, tileMap, 2);
  }

  get(name) {
    return this.sprites[name] || null;
  }
}
